plot( gfort(:,1), gfort(:,2), 'k', ...
      intel(:,1), intel(:,2), 'b', ...
      amd(:,1), amd(:, 2), 'r', ...
      mkl(:,1), mkl(:, 2), 'g', ...
      gfort4(:,1), gfort4(:, 2), 'k--', ...
      intel4(:,1), intel4(:,2), 'b--', ...
      acmlomp(:,1), acmlomp(:, 2), 'r--', ...
      mklomp(:,1), mklomp(:, 2), 'g--', ...      
      'LineWidth', 4)
  
xlabel('m','fontsize', 14)
ylabel('MFLOPS','fontsize', 14)
grid on
legend('gfortran', 'ifort', 'ACML', 'MKL', ...
     'gfortran-4t', 'ifort-4t', ...
     'ACML-4t', 'MKL-4t', 'fontsize', 14)